categories/urls.py
from django.urls import path

from categories import views

app_name = 'categories'

urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('movie/<slug:movie_slug>/',views.movie, name='movie'),
]

comments/urls.py
from comments import views

from django.urls import path

app_name = 'comments'
urlpatterns = [
     path('comments/', views.comment, name='comments'),
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    # path('about/',views.about, name='about')
]

my_project/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static


from my_project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('comment/', include('comments.urls', namespace='comment')),
    path('catalog/', include('categories.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user'))
]

if settings.DEBUG: 
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns  += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

categories/models.py
from django.db import models


class Categories(models.Model):

    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True,verbose_name='URL')

    class Meta:
        db_table = 'category'
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'
    
    def __str__(self):
        return self.name

class Movie(models.Model):

    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    grade = models.DecimalField(default=0.0, max_digits=3, decimal_places=2, verbose_name='Оценка')
    image = models.ImageField(upload_to='categories_images', blank=True, null=True, verbose_name='Изображение')
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE, verbose_name='Категория')

    class Meta:
        db_table = 'content'
        verbose_name = 'Контент'
        verbose_name_plural = 'Контент'
        ordering = ("id",)
    
    def __str__(self):
        return self.name
    
    def display_id(self):
        return f"{self.id:05}"

categories/views.py
from django.core.paginator import Paginator
from django.shortcuts import get_list_or_404, render

from categories.models import Movie
from categories.utils import q_search

def catalog(request, category_slug=None):

    page= request.GET.get('page',1)
    query = request.GET.get('q', None)

    if category_slug == 'all':
        categori = Movie.objects.all()
    elif query:
        categori = q_search(query)
    else:
        categori = get_list_or_404(Movie.objects.filter(category__slug=category_slug))
        
    paginator = Paginator(categori, 3)
    current_page = paginator.page(int(page))

    context = {
        'title': 'Home - Каталог',
        'categori': current_page,
        'slug_url': category_slug
    }
    return render(request, 'categories/catalog.html', context)


def movie(request, movie_slug):

    movie= Movie.objects.get(slug=movie_slug)

    context = {
        'movie': movie
    }
    return render(request, 'categories/movie.html', context=context)

categories/templates/categories/catalog.html
{% extends "bace.html" %}
{% load static %}
{% load categories_tegs %}

{% block content %}
    <div class="row">
        {% for movie in categori %}
                <!-- Карта -->
                <div class="col-lg-4 col-md-6 p-4">
                    <div class="card border-primary rounded custom-shadow">
                        {% if movie.image %}
                            <img src="{{movie.image.url}}" class="card-img-top" alt="...">
                        {% endif %}
                        <div class="card-body">
                            <a href="{% url "catalog:movie" movie.slug %}">
                                <p class="card-title">
                                    {% autoescape off %}
                                        {% if movie.headline %}
                                        {{movie.headline}}
                                        {% else %}
                                        {{movie.name}}
                                        {% endif %}
                                    {% endautoescape %}
                                </p>
                            </a>
                            <p class="card-text">
                                {% autoescape off %}
                                    {% if movie.bodyline %}
                                    {{movie.bodyline|truncatechars:100}}
                                    {% else %}
                                    {{movie.description|truncatechars:35}}
                                    {% endif %}
                                {% endautoescape %}
                                {% comment %} {{movie.description|truncatechars:35}} {% endcomment %}
                            </p>
                            <p class="product_id">id: {{movie.display_id}}</p>
                            <div class="d-flex justify-content-between">
                                <p><strong>{{movie.grade}}</strong></p>
                                <a href="#" class="btn">
                                    <img class="mx-1" src="{% static "deps/icons/comments.svg" %}" alt="Catalog Icon"
                                        width="32" height="32">
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}
 
    </div>
        <!-- Пагинация -->
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center my-4">
                <div class="custom-shadow d-flex">
                    <li class="page-item {% if not categori.has_previous %}disabled{% endif %}">
                    <a class="page-link" href="{% if categori.has_previous %}?{% change_params page=categori.previous_page_number %}{% else %}#{% endif %}"> Назад </a>
                    </li>
                    {% for page in categori.paginator.page_range %}
                        {% if page >= categori.number|add:-2 and page <= categori.number|add:2 %}                    
                            <li class="page-item {% if categori.number == page %} active {% endif %}">
                                <a class="page-link" href="?{% change_params page=page %}">{{ page }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    <li class="page-item {% if not categori.has_next %}disabled{% endif %}">
                        <a class="page-link" href="{% if categori.has_next %}?{% change_params page=categori.next_page_number %}{% else %}#{% endif %}"> Следующая </a>
                    </li>
                </div>
            </ul>
        </nav>
{% endblock content %}

{% block footer %}
    <footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white h5">Дипломная работа 2024</p>
        </div>
    </footer>
{% endblock footer %}

categories/templates/categories/movie.html
{% extends "bace.html" %}
{% load static %}

{% block content %}
    <div class="container mt-5">
        <div class="card mb-4 custom-shadow">
            <div class="row">
                <!-- Миниатюры -->
                <div class="col-md-4">
                    <img src="{{ movie.image.url }}"
                        class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">
                </div>
                <div class="col-md-4 ">
                    <p class="product_id mt-3">id: {{movie.display_id}}</p>
                </div>
                <!-- Увеличить изображение в модальном окне -->
                <div class="modal fade" id="imageModal1" tabindex="-1"
                    aria-labelledby="imageModal1Label" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="imageModal1Label">{{movie.name}}</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Закрыть"></button>
                            </div>
                            <div class="modal-body">
                                <img src="{{ movie.image.url }}"
                                    class="img-fluid" alt="Изображение 1">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Описание товара -->
            <div class="card-body">
                <p class="card-text">Оценка: <strong>{{movie.grade}}</strong></p>
                <h5 class="card-title">{{movie.name}}</h5>
                <p class="card-text">{{movie.description}}</p>
                <a href="{% url "comments:comments" %}" class="btn btn-dark add-to-cart">Оставить комментарий</a>
            </div>
        </div>
    </div>
{% endblock content %}